Repository jfrog/charts, pull requests merged in 2020-04, with the labels that each got.

#822 [ xray ] - Fix broken rabbitmq support when `rabbitmq.enabled=true`
  stable/xray/CHANGELOG.md
  stable/xray/Chart.yaml
  stable/xray/templates/_helpers.tpl
  stable/xray/templates/xray-statefulset.yaml
  stable/xray/values.yaml
Labels: bug

#825 [ artifactory-ha ] - Fix broken support for gcpServiceAccount for googleStorage
  stable/artifactory-ha/CHANGELOG.md
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
  stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
  stable/artifactory-ha/values.yaml
Labels: bug

#848 [distribution] - Add support to db existing secrets
  stable/distribution/CHANGELOG.md
  stable/distribution/Chart.yaml
  stable/distribution/README.md
  stable/distribution/templates/database-secrets.yaml
  stable/distribution/templates/distribution-statefulset.yaml
  stable/distribution/values.yaml
Labels: enhancement

#845 [artifactory-ha] fix useInstanceCredentials
  stable/artifactory-ha/CHANGELOG.md
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/values.yaml
  stable/artifactory/CHANGELOG.md
  stable/artifactory/Chart.yaml
  stable/artifactory/values.yaml
Labels: bug-fix, good first issue
