Repository jfrog/charts, pull requests merged in 2020-12, with the labels that each got.

#1268 [pipelines] Change semverCompare checks to support hosted Kubernetes
  stable/pipelines/CHANGELOG.md
  stable/pipelines/Chart.yaml
  stable/pipelines/templates/api-ingress.yaml
  stable/pipelines/templates/www-ingress.yaml
Labels: verified-looks-good

#1229 [pipelines] Add protocol to port names for istio
  stable/pipelines/CHANGELOG.md
  stable/pipelines/templates/api-ingress.yaml
  stable/pipelines/templates/api-service.yaml
  stable/pipelines/templates/pipelines-service-headless.yaml
  stable/pipelines/templates/pipelines-statefulset.yaml
  stable/pipelines/templates/vault-service-headless.yaml
  stable/pipelines/templates/vault-service.yaml
  stable/pipelines/templates/vault-statefulset.yaml
  stable/pipelines/templates/www-ingress.yaml
  stable/pipelines/templates/www-service.yaml
  stable/pipelines/values.yaml
Labels: verified-looks-good

#1228 [mission-control] Add protocol to port names for istio
  stable/mission-control/CHANGELOG.md
  stable/mission-control/Chart.yaml
  stable/mission-control/templates/mission-control-statefulset.yaml
  stable/mission-control/templates/mission-control-svc.yaml
Labels: to-be-tested

#1252 [distribution] Add protocol to port names for istio
  stable/distribution/CHANGELOG.md
  stable/distribution/Chart.yaml
  stable/distribution/templates/distribution-statefulset.yaml
  stable/distribution/templates/distribution-svc.yaml
Labels: verified-looks-good

#1303 [xray] 2.6.11 release
  stable/xray/CHANGELOG.md
  stable/xray/Chart.yaml
  stable/xray/README.md
Labels: Pre-unified-charts

#1311 Don't Merge [artifactory][artifactory-ha] Add gid support for artifactory statefulset
  stable/artifactory-ha/CHANGELOG.md
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
  stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
  stable/artifactory-ha/values.yaml
  stable/artifactory/CHANGELOG.md
  stable/artifactory/Chart.yaml
  stable/artifactory/templates/artifactory-statefulset.yaml
  stable/artifactory/values.yaml
Labels: 7.12.x- release, to-be-tested

#1300 [artifactory][artifactory-ha] Enable Open Metrics support
  stable/artifactory-ha/CHANGELOG.md
  stable/artifactory-ha/values.yaml
  stable/artifactory/CHANGELOG.md
  stable/artifactory/values.yaml
Labels: 7.12.x- release, verified-looks-good

#1242 Don't merge - [artifactory] Allow securityContext to be removed from statefulset with flag
  stable/artifactory-ha/CHANGELOG.md
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
  stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
  stable/artifactory-ha/values.yaml
  stable/artifactory/CHANGELOG.md
  stable/artifactory/Chart.yaml
  stable/artifactory/templates/artifactory-statefulset.yaml
  stable/artifactory/values.yaml
Labels: 7.12.x- release, verified-looks-good
