Repository jfrog/charts, pull requests merged in 2020-11, with the labels that each got.

#1269 [pipelines] 1.8.12 release
  stable/pipelines/CHANGELOG.md
  stable/pipelines/Chart.yaml
Labels: verified-looks-good

#1226 [artifactory][artifactory-ha] Adding protocols to port names for istio
  stable/artifactory-ha/CHANGELOG.md
  stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
  stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
  stable/artifactory-ha/templates/artifactory-service.yaml
  stable/artifactory-ha/templates/nginx-deployment.yaml
  stable/artifactory-ha/templates/nginx-service.yaml
  stable/artifactory/CHANGELOG.md
  stable/artifactory/templates/artifactory-service.yaml
  stable/artifactory/templates/artifactory-statefulset.yaml
  stable/artifactory/templates/nginx-deployment.yaml
  stable/artifactory/templates/nginx-service.yaml
Labels: verified-looks-good

#1267 [artifactory][artifactory-ha] Change semverCompare checks to support hosted Kubernetes
  stable/artifactory-ha/CHANGELOG.md
  stable/artifactory-ha/templates/ingress.yaml
  stable/artifactory/CHANGELOG.md
  stable/artifactory/templates/ingress.yaml
Labels: verified-looks-good

#1230 [artifactory][artifactory-ha] Make ServiceMonitors optional
  stable/artifactory-ha/CHANGELOG.md
  stable/artifactory-ha/README.md
  stable/artifactory-ha/templates/servicemonitor.yaml
  stable/artifactory-ha/values.yaml
  stable/artifactory/CHANGELOG.md
  stable/artifactory/README.md
  stable/artifactory/templates/servicemonitor.yaml
  stable/artifactory/values.yaml
Labels: verified-looks-good

#1262 [artifactory/ artifactory-ha] - Fix PostStartHookError
  stable/artifactory-ha/CHANGELOG.md
  stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
  stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
  stable/artifactory/CHANGELOG.md
  stable/artifactory/templates/artifactory-statefulset.yaml
Labels: bug, question, verified-looks-good

#1260 [artifactory/ artifactory-ha] Update check for making tls keypair to use nginx.https.enabled
  stable/artifactory-ha/CHANGELOG.md
  stable/artifactory-ha/templates/nginx-certificate-secret.yaml
  stable/artifactory-ha/templates/nginx-deployment.yaml
  stable/artifactory/CHANGELOG.md
  stable/artifactory/templates/nginx-certificate-secret.yaml
  stable/artifactory/templates/nginx-deployment.yaml
Labels: verified-looks-good

#1227 [xray] Add protocol to port names in for istio
  stable/xray/CHANGELOG.md
  stable/xray/templates/xray-statefulset.yaml
  stable/xray/templates/xray-svc.yaml
Labels: verified-looks-good

#1282 [artifactory][artifactory-ha] 6.23.3 release
  stable/artifactory-ha/CHANGELOG.md
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/README.md
  stable/artifactory/CHANGELOG.md
  stable/artifactory/Chart.yaml
  stable/artifactory/README.md
Labels: Pre-unified-charts

#1283 [artifactory-oss/jcr/cpp-ce] Update dependency Artifactory chart version to 8.10.1 (Artifactory 6.23.3)
  stable/artifactory-cpp-ce/CHANGELOG.md
  stable/artifactory-cpp-ce/Chart.yaml
  stable/artifactory-cpp-ce/README.md
  stable/artifactory-cpp-ce/requirements.lock
  stable/artifactory-cpp-ce/requirements.yaml
  stable/artifactory-jcr/CHANGELOG.md
  stable/artifactory-jcr/Chart.yaml
  stable/artifactory-jcr/README.md
  stable/artifactory-jcr/requirements.lock
  stable/artifactory-jcr/requirements.yaml
  stable/artifactory-oss/CHANGELOG.md
  stable/artifactory-oss/Chart.yaml
  stable/artifactory-oss/README.md
  stable/artifactory-oss/requirements.lock
  stable/artifactory-oss/requirements.yaml
Labels: verified-looks-good
